// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniformAPI.DataAccess;

#nullable disable

namespace UniformAPI.Migrations
{
    [DbContext(typeof(UniformContext))]
    partial class UniformContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("UniformAPI.Entities.Uniform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UniformDepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniformStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniformTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UniformDepartmentId");

                    b.HasIndex("UniformStatusId");

                    b.HasIndex("UniformTypeId");

                    b.ToTable("Uniforms");
                });

            modelBuilder.Entity("UniformAPI.Entities.UniformDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "A"
                        },
                        new
                        {
                            Id = 2,
                            Department = "B"
                        },
                        new
                        {
                            Id = 3,
                            Department = "C"
                        });
                });

            modelBuilder.Entity("UniformAPI.Entities.UniformStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Status = "In Use"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Maintenance"
                        });
                });

            modelBuilder.Entity("UniformAPI.Entities.UniformType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Dress"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Pants"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Shirt"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Waist"
                        });
                });

            modelBuilder.Entity("UniformAPI.Entities.Uniform", b =>
                {
                    b.HasOne("UniformAPI.Entities.UniformDepartment", "UniformDepartment")
                        .WithMany("Uniforms")
                        .HasForeignKey("UniformDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformAPI.Entities.UniformStatus", "UniformStatus")
                        .WithMany("Uniforms")
                        .HasForeignKey("UniformStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniformAPI.Entities.UniformType", "UniformType")
                        .WithMany("Uniforms")
                        .HasForeignKey("UniformTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniformDepartment");

                    b.Navigation("UniformStatus");

                    b.Navigation("UniformType");
                });

            modelBuilder.Entity("UniformAPI.Entities.UniformDepartment", b =>
                {
                    b.Navigation("Uniforms");
                });

            modelBuilder.Entity("UniformAPI.Entities.UniformStatus", b =>
                {
                    b.Navigation("Uniforms");
                });

            modelBuilder.Entity("UniformAPI.Entities.UniformType", b =>
                {
                    b.Navigation("Uniforms");
                });
#pragma warning restore 612, 618
        }
    }
}
